services:
  5etools:
    build: .
    container_name: 5etools
    ports:
      - "11014:80"
    volumes:
      - 5etools-data:/data
    environment:
      AUTO_PULL_INTERVAL: "3600"
      BUILD_SW: "true"
      BUILD_SEO: "false"
      SRC_REPO: https://github.com/5etools-mirror-3/5etools-src.git
      IMG_REPO: https://github.com/5etools-mirror-3/5etools-img.git
    restart: unless-stopped

volumes:
  5etools-data:
